name: Excavator

on:
  workflow_dispatch:
  schedule:
    - cron: "23 */6 * * *"

permissions:
  contents: write

jobs:
  excavate:
    runs-on: windows-latest
    steps:
      - name: Update manifests
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
